### ISSUE TITLE
Vercel error (Can't resolve '/vercel/.../.mdx-data/...json' ) when defaultLayout is TSX file

### ISSUE THREAD

**Issue by talentlessguy** [hashicorp/next-mdx-enhanced#61]
When I try to deploy my site on Vercel - I get an `Can't resolve .mdx-data/...json` error.

It doesn't happen locally with `pnpm` (I use it) - everything builds fine in both `prod` and `dev` environments.

I contacted the Vercel support. Support staff tried to build the project locally with `npm` and got this in output:

```
▲ v1rtl_site [master] NODE_ENV=production npm run build

> v1rtl.site@1.0.0 build /home/paulogdm/Codes/tmp/v1rtl_site
> next build

> Using external babel configuration
> Location: "/home/paulogdm/Codes/tmp/v1rtl_site/.babelrc"
Creating an optimized production build  

Failed to compile.

./.mdx-data/1069cf30b3afb243316ebb672e986d37.json
Module parse failed: Unexpected end of JSON input while parsing near ''
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
SyntaxError: Unexpected end of JSON input while parsing near ''
    at JSON.parse (<anonymous>)


> Build error occurred
Error: > Build failed because of webpack errors
    at build (/home/paulogdm/Codes/tmp/v1rtl_site/node_modules/next/dist/build/index.js:13:917)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! v1rtl.site@1.0.0 build: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v1rtl.site@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paulogdm/.npm/_logs/2020-06-04T20_46_56_918Z-debug.log
```

So it crashes when dependencies are installed and the project is built with `npm`.

As mentioned in the issue title, it happens in Vercel deployment as well:

```
2020-06-03T18:41:05.449Z  Failed to compile.
2020-06-03T18:41:05.449Z  
2020-06-03T18:41:05.449Z  ./pages/blog/index.tsx
2020-06-03T18:41:05.449Z  Module not found: Can't resolve '/vercel/fe67864/.mdx-data/115651746382137e132aae2ef68bd767.json' in '/vercel/fe67864/pages/blog'
2020-06-03T18:41:05.449Z  
2020-06-03T18:41:05.450Z  
2020-06-03T18:41:05.450Z  > Build error occurred
2020-06-03T18:41:05.451Z  Error: > Build failed because of webpack errors
2020-06-03T18:41:05.451Z      at build (/vercel/fe67864/node_modules/next/dist/build/index.js:13:917)
2020-06-03T18:41:05.479Z  error Command failed with exit code 1.
2020-06-03T18:41:05.479Z  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2020-06-03T18:41:05.489Z  Error: Command "yarn run build" exited with 1
2020-06-03T18:41:07.101Z  Done with "package.json"
```

The problematic page might be this one ([gh source](https://github.com/talentlessguy/v1rtl_site/blob/master/pages/blog/index.tsx)):

```jsx
// pages/blog/index.tsx
import { NextPage } from 'next'
import Link from 'next/link'
import 'isomorphic-unfetch'
import { frontMatter, MDXPost } from './*.mdx'

const formatPath = (p: string) => p.replace(/\.mdx$/, '')

const PageList: NextPage = () => {
  const posts = (frontMatter as MDXPost[]) || []

  return (
    <section>
      <h1>My Blog</h1>
      <div>
        {posts?.map((post) => (
          <Link key={post.title} href={formatPath(post.__resourcePath)}>
            <a  href={formatPath(post.__resourcePath)}>
                  <h2>{post.title}</h2>
                  <span>{post.date}</span>
            </a>
          </Link>
        ))}
      </div>
    </section>
  )
}

export default PageList
```

I use `babel-plugin-import-glob-array`, as it was recommended in readme.

More info can be found in [this issue](https://github.com/jescalan/babel-plugin-import-glob-array/issues/10)

**Comment by talentlessguy** [comment]
Related: https://github.com/hashicorp/next-mdx-enhanced/issues/45

**Comment by talentlessguy** [comment]
I found out why it happens. My `defaultLayout` was tsx extension

**Comment by talentlessguy** [comment]
seems not to be the reason of the problem.

still getting this even when both layout and next.js page is js:
```
Module not found: Can't resolve '/vercel/3f40fcdd/.mdx-data/13e766c2ac9b5a7678abbcc8093d5025.json' in '/vercel/3f40fcdd/pages'
```

**Comment by SiTaggart** [comment]
Same error, but I get it locally on my machine too when doing `next build`.

**Comment by talentlessguy** [comment]
I tried to make a [reproduction repository](https://github.com/talentlessguy/next-mdx-enhanced-repro) - it builds...

I contacted the author of `next-mdx-enhanced`, the reason why it happens is that is something messed up in layout file.

and I noticed that imported `*.mdx` which triggers the babel plugin, so this was the root of the issue.

closing it now

**Comment by talentlessguy** [comment]
@SiTaggart try checking your `layouts/index.tsx` file - probably something works wrong there

**Comment by daneden** [comment]
@talentlessguy did you end up fixing this in Vercel/prod too? I’m running into the same issue and am 100% certain my layout files don’t have TS errors (based on the fact that they compiled just fine before using the `import-glob-array` Babel plugin).

It looks like I can get around this as others have by running `next build` twice, but that’s literally doubling the work of the build step.

**Comment by SiTaggart** [comment]
Same here. Doesn’t seem to be a problem with the layout as it compiles with TS just fine, and also builds just fine (after you’ve run build twice to generate the mdx data correctly.)

Pretty inconsistent locally. Sometimes it builds just fine, other times needs two builds.

Pretty frustrating

**Comment by talentlessguy** [comment]
@daneden This `Can't resolve mdx-data...json` can have different causes.

Yes, I got it working on prod, it builds on Vercel just fine

**Comment by zeekrey** [comment]
I got the same issue. For me the problem disappears if a don't `import { frontMatter as testData } from './test.mdx'`. Looks like the current setup is not able to import mdx files. Can someone post a working next.config.js? This is mine (as mentioned in the readme):

```javascript
// next.config.js
const withMdxEnhanced = require('next-mdx-enhanced')

module.exports = withMdxEnhanced({
    layoutPath: 'src/layouts',
    defaultLayout: true,
    fileExtensions: ['mdx'],
    remarkPlugins: [],
    rehypePlugins: [],
    usesSrc: false,
    extendFrontMatter: {
        process: (mdxContent, frontMatter) => {},
        phase: 'prebuild|loader|both',
    },
    reExportDataFetching: false,
})(/* your normal nextjs config */)
```

Is it necessary to add:

```javascript
const withMDX = require('@next/mdx')({
     extension: /\.mdx?$/,
 })
```

**Comment by jescalan** [comment]
I have been alerted to an issue with Vercel caching here, and have reproduced it in one place. There might be a fix coming down the line for this. For now I have consistently been able to resolve with a rebuild in Vercel.

**Comment by DavidWells** [comment]
Getting the same issue. 

```
import { frontMatter } from '../../pages/blog/**/*.mdx'
```

This import was working but now doesn't ¯\_(ツ)_/¯

Fails with 

```
Module not found: Can't resolve '/Users/xyz/123/site/.mdx-data/f637f29d0689b81304b70e74ad2a360c.json' in '/Users/xyz/123/site/src/utils'
```

This is odd because I haven't changed anything about the project. 

Is there a way to purge the cache? I've `rm -rf .next` but the error remains. `next dev` and `next build` both fail consistently on my machine 😅

**Comment by jescalan** [comment]
@DavidWells can you share a minimal reproduction?

**Comment by DavidWells** [comment]
I've switched to using `globby` + `getStaticProps` vs the babel plugin for the time being. 

```
import fs from 'fs'
import path from 'path'
import { promisify } from 'util'
import getFrontMatter from 'gray-matter'
import globby from 'globby'

export async function getStaticProps({ ...ctx }) {

  const blogFiles = await globby(['pages/blog/*.md', 'pages/blog/*.mdx'])
  const readFile = promisify(fs.readFile)

  const blogPostInfo = await Promise.all(blogFiles.map(async (file) => {
    const content = await readFile(path.resolve(file), 'utf-8')
    const data = getFrontMatter(content)
    return {
      id: file.replace(/^pages/, '').replace(/.mdx?$/, ''),
      ...data.data
    }
  }))

  return {
    props: {
      blogPosts: blogPostInfo,
    },
  }
}
```

**Comment by jescalan** [comment]
This should be resolved by the latest release!

**Comment by dvargas92495** [comment]
Just upgraded to 5.0, still seeing this issue. deleted `.mdx-data`, cleaned `.next` and restarted. the `mdx-data` folder is in the new location but appears empty

**Comment by dvargas92495** [comment]
oh jk. I had another warning up to call stack that I thought was unrelated. But resolving that unblocked me

**Comment by kamal-choudhary** [comment]
I was also facing the same error. Whenever I added the line "./blog.posts/*.mdx", I was getting error like "Can't resolve '/site/.next/cache/mdx-data/5dda69dc891556dd9f63950c580a2748.json' in '/site/Components/context/data'.

How I was able to fix it?

I was missing the babel plugin "babel-plugin-import-glob-array":.

I added this line of code:

"babel-plugin-import-glob-array": "^0.2.0"

under devDependenices of package.json file. Don't forget to install the plugin.

And then I also added this line of code:

  "plugins": ["import-glob-array"]

in the .babelrc file. 

Doing these two things fixed the error.

Note: I was getting errors while I was running "npm run dev".
